[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

optimizer = true
optimizers_runs = 200
fs_permissions = [{ access = "read-write", path = "./"}]

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1 }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
